---
- hosts: local
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true
  sudo_user: "{{project_name}}"

  tasks:
  - name: Pull sources from the repository.
    git: repo=${project_repo} dest=${project_root}/app/ version={{branch}}
    # when: "$vm == 0"
    # notify:
    #   - restart web frontend

  # - name: Upload configuration.
  #   copy: src=webapp_settings/local_settings.${nickname}.py dest=${project_root}/app/webapp/local_settings.py
  #   when: "$vm == 0"

  # - name: Upgrade the virtualenv.
  #   pip: requirements=${project_root}/app/requirements.txt virtualenv=${project_root}/env/

  # - name: Sync Django database.
  #   shell: ${project_root}/env/bin/python ${project_root}/app/webapp/manage.py syncdb --migrate --noinput

  # - name: Generate Django media.
  #   shell: ${project_root}/env/bin/python ${project_root}/app/webapp/manage.py generatemedia

  handlers:
    - include: handlers.yml