---
- hosts: local
  vars_files:
    - vars.yml
    - vagrant-vars.yml
  gather_facts: false
  sudo: true

  tasks:
  - name: Create the project directory.
    file: state=directory path={{project_root}}

  - name: Create user.
    user: home={{project_root}}/home/ name={{project_name}} state=present

  - name: Update the project directory.
    file: group={{project_name}} owner={{project_name}} mode=755 state=directory path={{project_root}}

  - name: Create the code directory.
    file: group={{project_name}} owner={{project_name}} mode=755 state=directory path={{project_root}}/app/

  - name: Create the .ssh directory
    file: group={{project_name}} owner={{project_name}} mode=755 state=directory path={{project_root}}/home/.ssh/

  - name: Create the known_hosts file.
    file: path={{project_root}}/home/.ssh/known_hosts owner={{ project_name }} group={{ project_name }} state=touch

  - name: Add known hosts to known_hosts file
    lineinfile: dest={{project_root}}/home/.ssh/known_hosts regexp=^${item.host} line="${item.line}"
    with_items:
    - { "host": "bitbucket.org", "line": "bitbucket.org,131.103.20.167 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==" }

  - name: Copying deploy key
    copy: src={{deploy_key}} dest={{project_root}}/home/.ssh/id_rsa owner={{project_name}} group={{project_name}} mode=0600

  - name: workaround to install postgresql with locale set 
    shell: LANG=$locale LC_COLLATE=$locale LC_CTYPE=$locale LC_MESSAGES=$locale LC_MONETARY=$locale LC_NUMERIC=$locale LC_TIME=$locale LC_ALL=$locale  apt-get install -y postgresql 


  - name: Install required system packages.
    apt: pkg=${item} state=installed update-cache=yes
    with_items: "${system_packages}"
  - name: Install required system packages for Vagrant.
    apt: pkg=${item} state=installed update-cache=yes
    with_items: "${vagrant_packages}"

  - name: Install required Python packages.
    easy_install: name=${item}
    with_items: "{{ python_packages }}"

    #copy key for git repository
    #setup database data

  - name: Install nginx configuration file.
    template: src=files/conf/nginx.conf.j2 dest=/etc/nginx/sites-enabled/{{ project_name }}
    #notify: restart nginx

  # - name: Install init scripts.
  #   copy: src=files/init/${item}.conf dest=/etc/init/${project_name}_${item}.conf
  #   with_items: ${initfiles}

  # - name: Create database.
  #   shell: ${project_root}/env/bin/python ${project_root}/app/webapp/manage.py sqlcreate --router=default | sudo -u postgres psql

#   handlers:
#     - include: handlers.yml

- include: deploy.yml

- hosts: local
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true
  sudo_user: postgres

  tasks:
  - include: nessmap-provision.yml

  # - name: Restart services.
  #   service: name={{project_name}}_{{item}} state=restarted
  #   with_items: "{{initfiles}}"